#ifndef MESSAGE_COMMON_H_
#define MESSAGE_COMMON_H_

#define HEAD_MAGIC 0x11223344

enum body_type
{
	MsgCommon								= 1,
	MsgConnectQuery							= 2,
	MsgConnectReply							= 3,
	MsgAddTypeQuery							= 4,
	MsgAddTypeReply							= 5,
	MsgDeleteTypeQuery						= 6,
	MsgDeleteTypeReply						= 7,
	MsgGetTypesNumQuery						= 8,
	MsgGetTypesNumReply						= 9,
	MsgGetTypesQuery						= 10,
	MsgGetTypesReply						= 11,
	MsgAddTableQuery						= 12,
	MsgAddTableReply						= 13,
	MsgDeleteTableQuery						= 14,
	MsgDeleteTableReply						= 15,
	MsgGetTablesNumQuery					= 16,
	MsgGetTablesNumReply					= 17,
	MsgGetTablesQuery						= 18,
	MsgGetTablesReply						= 19,
	MsgAddPointQuery						= 20,
	MsgAddPointReply						= 21,
	MsgDeletePointQuery						= 22,
	MsgDeletePointReply						= 23,
	MsgSearchPointsNumQuery					= 24,
	MsgSearchPointsNumReply					= 25,
	MsgSearchPointsQuery					= 26,
	MsgSearchPointsReply					= 27,
	MsgSearchPointsNumBYIDQuery				= 28,
	MsgSearchPointsByIDQuery				= 29,
	MsgGetTypeByIDQuery						= 30,
	MsgGetTypeByIDReply						= 31,
	MsgWriteNewDatasQuery					= 32,
	MsgWriteNewDatasReply					= 33,
	MsgReadNewDatasQuery					= 34,
	MsgReadNewDatasReply					= 35,
	MsgReadDatasNumQuery					= 36,
	MsgReadDatasNumReply					= 37,
	MsgReadDatasQuery						= 38,
	MsgReadDatasReply						= 39,
	MsgGetDataFileNumsQuery					= 40,
	MsgGetDataFileNumsReply					= 41,
	MsgDataFileInfosQuery					= 42,
	MsgDataFileInfosReply					= 43,
	MsgWriteOldDatasQuery					= 44,
	MsgWriteOldDatasReply					= 45,
	MsgRemoveDatasQuery						= 46,
	MsgRemoveDatasReply						= 47,
	MsgAddFileQuery							= 48,
	MsgAddFileReply							= 49,
	MsgCreateFileQuery						= 50,
	MsgCreateFileReply						= 51,
	MsgRebuildIndexQuery					= 52,
	MsgRebuildIndexReply					= 53,
	MsgDeleteFileQuery						= 54,
	MsgDeleteFileReply						= 55,
	MsgGetTableByIDQuery					= 56,
	MsgGetTableByIDReply					= 57,
};


#endif /* MESSAGE_COMMON_H_ */
